[package]
name = "nftracker-simulator"
version = "0.1.0"
authors = ["Bodo Junglas <junglas@objectcode.de>"]
edition = "2018"

[dependencies]
clap = "2.33"
log = "0.4"
env_logger = "0.6"
rand = "0.7"
rand_distr = "0.2"
